type=page
status=published
title=Prerequisite Tasks for Completing This Tutorial
next=java-ee.html
prev=intro001.html
~~~~~~
= Prerequisite Tasks for Completing This Tutorial


[[GCQZL]][[prerequisite-tasks-for-completing-this-tutorial]]

Prerequisite Tasks for Completing This Tutorial
-----------------------------------------------

To complete this tutorial, you need to complete the following tasks
first:

* link:#software-compatibility[See the software compatibility notice]
* link:#get-the-java-ee-8-sdk[Get the Java EE 8 SDK]
* link:#install-the-netbeans-ide-distribution-for-java-ee[Install the NetBeans IDE distribution for Java EE]
* link:#add-glassfish-server-as-a-server-in-netbeans-ide[Add GlassFish Server as a server in NetBeans IDE]
////
* link:#get-the-latest-updates-to-this-tutorial[Get the latest updates to this tutorial]
////

[[software-compatibility]]

Software Compatibility Notice
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This tutorial is compatible with the following software:

[width="55%",cols="30%,60%"]
|=======================================================================
|*Software* |*Version*
|link:http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java Development Kit (JDK)] | 8 update 144 (8u144) or greater
|link:https://javaee.github.io/glassfish/[GlassFish Server] | 5.0 or greater
|link:https://netbeans.org/[NetBeans IDE] | 8.2 or greater
|link:https://eclipse.org/ide/[Eclipse IDE] | 4.7.0 or greater

|=======================================================================

[[GCRNX]][[get-the-java-ee-8-sdk]]

Get the Java EE 8 SDK
~~~~~~~~~~~~~~~~~~~~~

To get the Java EE 8 SDK, go to
`http://www.oracle.com/technetwork/java/javaee/downloads/`. Download and
install the SDK. The location where you install it is typically
`glassfish5` in your home directory, but you can change this.

The tutorial is installed in the `docs/firstcup` directory of your SDK
installation.

[[GCRNU]][[install-the-netbeans-ide-distribution-for-java-ee]]

Install the NetBeans IDE Distribution for Java EE
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

To get NetBeans IDE, go to `https://netbeans.org/downloads/` and
download the Java EE distribution. Install this distribution.

[[GIOEW]][[add-glassfish-server-as-a-server-in-netbeans-ide]]

Add GlassFish Server as a Server in NetBeans IDE
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Once you have all the necessary downloads, you must configure NetBeans
IDE and get the latest tutorial updates.

To run this tutorial in NetBeans IDE, you must register your GlassFish
Server installation as a NetBeans server instance. Follow these
instructions to register the GlassFish Server in NetBeans IDE.

1.  From the *Tools* menu, select *Servers*.
2.  In the Servers dialog, click *Add Server*.
3.  Under *Choose Server*, select *GlassFish Server* and click *Next*.
4.  Under *Server Location*, browse to or enter the location of your
GlassFish Server installation.
5.  Click *Next*.
6.  Under *Domain Location*, select the default domain, `domain1`.
7.  Click *Finish*.

////
[[GIMVN]][[get-the-latest-updates-to-this-tutorial]]

Get the Latest Updates to this Tutorial
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Check for any updates to this tutorial by using the Update Center
included with the Java EE 8 SDK.

1.  In NetBeans IDE, select the *Services* tab and expand the *Servers*
node.
2.  Right-click the GlassFish Server instance and select *View Domain
Update Center* to display the Update Tool.
3.  In the tree, select *Available Updates* to display a list of updated
packages.
4.  Look for updates to the First Cup for Java EE 8
(`javaee-firstcup-tutorial`) package.
5.  If there is an updated version, select First Cup for Java EE 8
(`javaee-firstcup-tutorial`) and click *Install*.
////
